Repository ArielHorwitz/botroyale, pull requests merged in 2022-08, with the labels that each got.

#61 Fix/windows font zoom crash
  bots/crazee_bot_003.py
  bots/crazee_bot_alpha.py
  bots/crazee_bot_legacy.py
  bots/idle_bot.py
  gui/battle/tilemap.py
Labels: bug

#62 New docs, refactoring
  .gitignore
  README.md
  __init__.py
  api/__init__.py
  api/actions.py
  api/bots.py
  api/gui.py
  api/logging.py
  api/time_test.py
  bots/__init__.py
  bots/random_bot.py
  docs/guides/battle.md
  docs/guides/brc.md
  docs/guides/custom_script.md
  docs/guides/simple_bot.md
  docs/templates/config.mako
  docs/templates/html.mako
  logic/__init__.py
  logic/battle.py
  logic/battle_manager.py
  logic/game.py
  logic/map_editor.py
  logic/maps.py
  logic/prng.py
  logic/state.py
  requirements.txt
  run/__init__.py
  run/cli.py
  run/docs.py
  run/example.py
  run/gui.py
  run/guibase.py
  run/makedocs.py
  util/__init__.py
  util/file.py
  util/hexagon.py
  util/settings.py
  util/time.py
Labels: documentation, enhancement

#65 Fixes
  README.md
  api/time_test.py
  assets/fonts/LICENCE.txt
  assets/fonts/firacode-mono-bold.ttf
  assets/fonts/firacode-mono.ttf
  assets/fonts/liberation-bold.ttf
  assets/fonts/liberation-mono-bold.ttf
  assets/fonts/liberation-mono.ttf
  assets/fonts/liberation.ttf
  bots/__init__.py
  bots/idle_bot.py
  bots/ninja_bot.py
  bots/random_bot.py
  gui/__init__.py
  gui/battle/panel.py
  gui/battle/tilemap.py
  gui/kex/widgets.py
  gui/menubar.py
  logic/battle.py
  logic/battle_manager.py
  logic/game.py
  logic/maps.py
  run/__init__.py
  run/cli.py
  run/docs.py
  run/example.py
  run/gui.py
  run/guibase.py
  run/makedocs.py
  util/file.py
Labels: bug, documentation
